### ISSUE TITLE
春松客服 5000 字介绍，纯字，没有图

### ISSUE THREAD

**Issue by hailiang-wang** [cskefu/handouts#3]
# 面向

企业客服主管，了解春松客服。

# 大纲

### 中国本土团队自主研发

春松客服是北京华夏春松于 2018 年发布的开源项目，目的是帮助企业上线智能客服系统。 2022 年，春松客服开源社区成立，目前春松客服由春松客服技术委员会领导，核心开发者来自开源社区，实践与客户、合伙伙伴共建社区。

### 最有价值开源项目

至 2022 年 10 月，春松客服在企业中部署超过 1.8 万次，上线客户超过 500 家，是 GitHub 上最受欢迎的中文开源客服系统。因开源、云原生架构和功能丰富受到广泛好评，在 Gitee 上赢得最有价值项目奖项。

### 愿景

策略：开源加云原生。为什么是开源加云原生方案：[https://www.cskefu.com/2022/04/11/cskefu-opensource-plus-cloud-model/](https://www.cskefu.com/2022/04/11/cskefu-opensource-plus-cloud-model/)

## 客户案例

[富盈证券上线春松客服](https://mp.weixin.qq.com/s/t4J_qPaN6on_yTz6s6GSew)

[江北新区研创园](https://mp.weixin.qq.com/s/MSC2E46Y1soeKsfJdntcow)

[高科华烨](https://mp.weixin.qq.com/s/7_eCxA3ylNaxCR48h3eqNw)

[深圳尔雅](https://mp.weixin.qq.com/s/9afFcXrQRQHchFPW4usSxg)

### 设计理念

[https://www.cskefu.com/2022/09/12/cskefu-philosophy/](https://www.cskefu.com/2022/09/12/cskefu-philosophy/)

### 功能

https://docs.cskefu.com/docs/

文本可参考：

文件：[https://github.com/cskefu/handouts/tree/master/docs/manuals/春松客服_用户使用文档_20220428.docx](https://github.com/cskefu/handouts/tree/master/docs/manuals/春松客服_用户使用文档_20220428.docx)

## 未来计划

愿景，新版本

**Comment by hailiang-wang** [comment]
增加文件 placeholder: 1_3_春松客服_5000字介绍.md。

[2022_11_25_SH_中国数字化创新博览会/1_3_春松客服_5000字介绍.md](https://github.com/cskefu/handouts/tree/master/activities/2022_11_25_SH_%E4%B8%AD%E5%9B%BD%E6%95%B0%E5%AD%97%E5%8C%96%E5%88%9B%E6%96%B0%E5%8D%9A%E8%A7%88%E4%BC%9A/1_3_春松客服_5000字介绍.md)

@SAMZONG 你写到文件 1_3_春松客服_5000字介绍.md 吧，然后我再转成 WORD，使用 WORD 对媒体平台伙伴方便。

**Comment by SAMZONG** [comment]
DONE.
